# ABOUTME: GitHub Actions workflow for building and deploying MkDocs site to GitHub Pages
# ABOUTME: Uses uv for dependency management and automatic deployment on push to main/master
name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - uses: astral-sh/setup-uv@v5
      - run: uv sync --locked
      - run: uv run mkdocs gh-deploy --force
